function MachineIDOutput(In, Time, MachineID, IDnumMatch)
Path = [In.OutputPath, '\SYSUPolynya_s3125_', datestr(Time, 'yyyymmdd')];
MachineID(In.SICFile.LandMask) = NaN;
nccreate(Path, 'MachineID', ...
    'Dimensions', {'x', size(MachineID, 1),'y', size(MachineID, 2)}, ...
    'Datatype', 'uint32', ...
    'DeflateLevel', 3); 
ncwrite(Path, 'MachineID', MachineID)
nccreate(Path, 'M-M_MapTable', ...
    'Dimensions', {'rows', length(IDnumMatch.Give),'columns', 2}, ...
    'Datatype', 'uint32', ...
    'DeflateLevel', 3); 
ncwrite(Path, 'M-M_MapTable', IDnumMatch.Give)
nccreate(Path, 'Lon', ...
    'Dimensions', {'x', size(MachineID, 1),'y', size(MachineID, 2)}, ...
    'Datatype', 'single', ...
    'DeflateLevel', 5); 
ncwrite(Path, 'Lon', In.SICLon)
nccreate(Path, 'Lat', ...
    'Dimensions', {'x', size(MachineID, 1),'y', size(MachineID, 2)}, ...
    'Datatype', 'single', ...
    'DeflateLevel', 5); 
ncwrite(Path, 'MachineID', In.SICLat)
fileattrib(Path,'+w');
ncwriteatt(Path, 'MachineID', 'Description', 'The Machine ID of polynyas');
ncwriteatt(Path, 'M-M_MapTable', 'Description', ...
    ['The table for the mapping from Machine ID to Manual ID. ', ...
    'The first column shows the Machine ID and the second one shows the Manual ID.']);
ncwriteatt(Path, 'Lon', 'Description', 'Longitudes');
ncwriteatt(Path, 'Lat', 'Description', 'Latitudes');
end